### ISSUE TITLE
Logging error during run keras mnist

### ISSUE THREAD

**Issue by sstolpovskiy** [SkymindIO/SKIL_Examples#7]
Hi all, 

I'm trying to run :
SKIL_Examples/skil_mnist_python_app/notebook/python_keras_tf_mnist.json

Downloading data from https://s3.amazonaws.com/img-datasets/mnist.npz
Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-295759292083689632.py", line 367, in <module>
    if not hasattr(sys.stdout, "isatty"):
Exception: Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-295759292083689632.py", line 355, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 9, in <module>
  File "/opt/skil/miniconda/lib/python2.7/site-packages/keras/datasets/mnist.py", line 17, in load_data
    file_hash='8a61469f7ea1b51cbae51d4f78837e45')
  File "/opt/skil/miniconda/lib/python2.7/site-packages/keras/utils/data_utils.py", line 220, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "/opt/skil/miniconda/lib/python2.7/site-packages/keras/utils/data_utils.py", line 68, in urlretrieve
    for chunk in chunk_read(response, reporthook=reporthook):
  File "/opt/skil/miniconda/lib/python2.7/site-packages/keras/utils/data_utils.py", line 60, in chunk_read
    reporthook(count, chunk_size, total_size)
  File "/opt/skil/miniconda/lib/python2.7/site-packages/keras/utils/data_utils.py", line 213, in dl_progress
    ProgressTracker.progbar = Progbar(total_size)
  File "/opt/skil/miniconda/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 270, in __init__
    self._dynamic_display = (sys.stdout.isatty() or
AttributeError: 'Logger' object has no attribute 'isatty'

I manually download this set and put into 

However at next run it is still getting this error:
_________________________________________________________________
Train on 60000 samples, validate on 10000 samples
Epoch 1/5
Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-295759292083689632.py", line 367, in <module>
    if not hasattr(sys.stdout, "isatty"):
Exception: Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-295759292083689632.py", line 355, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 34, in <module>
  File "/opt/skil/miniconda/lib/python2.7/site-packages/keras/models.py", line 893, in fit
    initial_epoch=initial_epoch)
  File "/opt/skil/miniconda/lib/python2.7/site-packages/keras/engine/training.py", line 1631, in fit
    validation_steps=validation_steps)
  File "/opt/skil/miniconda/lib/python2.7/site-packages/keras/engine/training.py", line 1161, in _fit_loop
    callbacks.on_epoch_begin(epoch)
  File "/opt/skil/miniconda/lib/python2.7/site-packages/keras/callbacks.py", line 59, in on_epoch_begin
    callback.on_epoch_begin(epoch, logs)
  File "/opt/skil/miniconda/lib/python2.7/site-packages/keras/callbacks.py", line 276, in on_epoch_begin
    verbose=self.verbose)
  File "/opt/skil/miniconda/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 270, in __init__
    self._dynamic_display = (sys.stdout.isatty() or
AttributeError: 'Logger' object has no attribute 'isatty'

I'm using SKIL server in docker container with persisted storage.

**Comment by sstolpovskiy** [comment]
This related to 1.0.1 version. At 1.0.2 is not reproduced.
