### ISSUE TITLE
python_keras_tf_mnist.json : skilContext.addEvaluationToModel gives error

### ISSUE THREAD

**Issue by RobAltena** [SkymindIO/SKIL_Examples#9]
When running the skilContext.addEvaluationToModel cell in python_keras_tf_mnist.json 

`Traceback (most recent call last):
 File "/tmp/zeppelin_pyspark-4124872881856933230.py", line 367, in <module>
    raise Exception(traceback.format_exc())
Exception: Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-4124872881856933230.py", line 360, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 1, in <module>
  File "/opt/skil/miniconda/lib/python2.7/site-packages/skil/__init__.py", line 152, in addEvaluationToModel
    e = self.Evaluation(nd_y.shape[1])
TypeError: 'JavaMember' object does not support indexing`

**Comment by jpatanooga** [comment]
Interesting. I have run this on my Azure install of SKIL and its ok. what platform are you running SKIL  on?

**Comment by RobAltena** [comment]
Now the plot thickens: Azure install of Skill. Let's make sure the master has a look now: @wmeddie .
